swagger: "2.0"
# Added by API Auto Mocking Plugin
info:
  description: hello, world
  termsOfService: "https://github.com/odditypark"
    
  version: "1.0.0"
  title: oklark.api
paths:
  /{ident}:
    get:
      tags: 
        - ident
      summary: ident info
      parameters:
        - name: ident
          in: path
          description: User Name
          required: true
          type: string
      responses:
        "200":
          description: ident info
          schema:
            type: object
            example: {
              name: 'Bowie',
              username: 'davidbowie',
              publickey: '475349a9b3daf719bf2d21f46f958dc769c6a8eba103c7c72bdf697e04cecc23',
              articles: [
                'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
                '3e23e8160039594a33894f6564e1b1348bbd7a0088d42c4acb73eeaed59c009d',
                '2e7d2c03a9507ae265ecf5b5356885a53393a2029d241394997265a1a25aefc6'
              ]
            }
    put: 
      tags: 
        - ident
      summary: update ident info
      description: def
      parameters:
        - name: ident
          in: path
          description: User Name
          required: true
          type: string
        - name: body
          required: true
          in: body
          schema:
            example: {
              username: 'mercury',
              publickey: '475349a9b3daf719bf2d21f46f958dc769c6a8eba103c7c72bdf697e04cecc23'
            }
      responses:
        200:
          description: 'return token'
          schema:
            type: object
            example: {
              token: "475349a9b3daf719bf2d21f46f958dc769c6a8eba103c7c72bdf697e04cecc23"
            }      
    post:
      tags: 
        - ident
      summary: new article.
      description: def
      parameters:
        - name: ident
          in: path
          description: User Name
          required: true
          type: string
        - name: body
          required: true
          in: body
          schema:
            example: {
              username: 'mercury',
              publickey: '475349a9b3daf719bf2d21f46f958dc769c6a8eba103c7c72bdf697e04cecc23'
            }
      responses:
        200:
          description: 'return token'
          schema:
            type: object
            example: {
              token: "475349a9b3daf719bf2d21f46f958dc769c6a8eba103c7c72bdf697e04cecc23"
            }
  /{ident}/{number}:
    get:
      tags: 
        - article
      summary: ident info
      parameters:
        - name: ident
          in: path
          description: User Name
          required: true
          type: string
        - name: number
          in: path
          description: article nuumber
          required: true
          type: string
      responses:
        "200":
          description: ident info
          schema:
            type: object
            example: {
              name: 'Bowie',
              username: 'davidbowie',
              publickey: '475349a9b3daf719bf2d21f46f958dc769c6a8eba103c7c72bdf697e04cecc23',
              articles: [
                'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
                '3e23e8160039594a33894f6564e1b1348bbd7a0088d42c4acb73eeaed59c009d',
                '2e7d2c03a9507ae265ecf5b5356885a53393a2029d241394997265a1a25aefc6'
              ]
            }
    post:
      tags: 
        - article
      parameters:
        - name: ident
          in: path
          required: true
          type: string
        - name: number
          in: path
          required: true
          type: string
      summary: update article
      responses:
        200:
          description: OK
    delete:
      tags: 
        - article
      parameters:
        - name: ident
          in: path
          description: User Name
          required: true
          type: string
        - name: number
          in: path
          description: article nuumber
          required: true
          type: string
      summary: delete article
      description:  world
      responses:
        200:
          description: OK
    